### ISSUE TITLE
An1E_2019 sollte ein neuer stand des bisherigen Repos An1E sein

### ISSUE THREAD

**Issue by dav1d-wright** [HSR-Stud/An1E_2019#1]
Die Version 2019 der Zusammenfassung des Moduls An1E sollte ein neuer Stand des Repos www.github.com/hsr-stud/An1E sein, kein eigenes Repo. Genau dafür ist die Versionsverwaltung (wie z.B. Git) da.

@pescara @Dev4Future

**Comment by NaoPross** [comment]
Discussion at https://github.com/HSR-Stud/An2E_2020/issues/1
